import Anthropic from '@anthropic-ai/sdk';

// Initialize Anthropic client
export function createAnthropicClient() {
  const apiKey = process.env.ANTHROPIC_API_KEY;

  if (!apiKey) {
    throw new Error('Missing ANTHROPIC_API_KEY environment variable');
  }

  return new Anthropic({
    apiKey,
  });
}

// Singleton instance
let anthropicClient: Anthropic | null = null;

export function getAnthropicClient() {
  if (!anthropicClient) {
    anthropicClient = createAnthropicClient();
  }
  return anthropicClient;
}

export interface ClaudeCallOptions {
  systemPrompt?: string;
  temperature?: number;
  maxTokens?: number;
}

// Helper function for making Claude API calls
export async function callClaude(
  userMessage: string,
  options: ClaudeCallOptions = {},
): Promise<string> {
  const client = getAnthropicClient();

  try {
    const response = await client.messages.create({
      model: 'claude-sonnet-4-5-20250929',
      max_tokens: options.maxTokens || 2048,
      temperature: options.temperature || 0.7,
      system: options.systemPrompt || 'You are a helpful assistant.',
      messages: [
        {
          role: 'user',
          content: userMessage,
        },
      ],
    });

    // Extract text content from response
    const textContent = response.content.find((block) => block.type === 'text');
    if (!textContent || textContent.type !== 'text') {
      throw new Error('No text content in Claude response');
    }

    return textContent.text;
  } catch (error) {
    console.error('Error calling Claude API:', error);
    throw error;
  }
}

// Helper function for structured analysis
export async function analyzeWithClaude(
  topic: string,
  context: string,
  instructions: string,
): Promise<string> {
  const systemPrompt = `You are an expert business analyst specializing in lead qualification and research.
You provide structured, actionable insights based on company research and lead information.
Be concise, specific, and data-driven in your analysis.`;

  const userMessage = `Topic: ${topic}

Context:
${context}

Instructions:
${instructions}

Please provide a structured response.`;

  return callClaude(userMessage, {
    systemPrompt,
    temperature: 0.5,
    maxTokens: 2048,
  });
}

// Helper for JSON generation from Claude
export async function generateJSONWithClaude(
  prompt: string,
  schema: string,
): Promise<Record<string, unknown>> {
  const systemPrompt = `You are a JSON generation assistant. 
You must respond ONLY with valid JSON that matches the provided schema. 
Do not include any markdown, explanations, or additional text.`;

  const userMessage = `Generate JSON data for the following:

${prompt}

Schema:
${schema}

Respond with ONLY the JSON object, no other text.`;

  const response = await callClaude(userMessage, {
    systemPrompt,
    temperature: 0.3,
    maxTokens: 2048,
  });

  try {
    // Remove markdown code blocks if present
    let jsonStr = response.trim();
    if (jsonStr.startsWith('```json')) {
      jsonStr = jsonStr.slice(7); // Remove ```json
    }
    if (jsonStr.startsWith('```')) {
      jsonStr = jsonStr.slice(3); // Remove ```
    }
    if (jsonStr.endsWith('```')) {
      jsonStr = jsonStr.slice(0, -3); // Remove trailing ```
    }

    return JSON.parse(jsonStr);
  } catch {
    console.error('Failed to parse Claude JSON response:', response);
    throw new Error('Invalid JSON generated by Claude');
  }
}
